executable    = BatchRun_MergedNtuples.sh
universe      = vanilla
output        = BatchLog/Merge.$(OPTION).$(ClusterId).$(ProcId).out
error         = BatchLog/Merge.$(OPTION).$(ClusterId).$(ProcId).err
log           = BatchLog/Merge.$(ClusterId).log
stream_output = True
stream_error  = True

environment = "JOBWORKDIR=$ENV(PWD)"

arguments = $(OPTION)

NCORES = 1
request_cpus = $(NCORES)

+JobFlavour = "microcentury"
queue OPTION from (
Nominal
)


#+JobFlavour = "longlunch"
#queue OPTION from (
#Syst
#)